name: python with docker build

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
    - name: checkout-code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t ravindradevops72/ravi-image:v11 .

    - name: Docker Login  
      run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

    - name: Push Docker Image
      run: docker push ravindradevops72/ravi-image:v11   


      