name: python with docker build

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
    - name: checkout-code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t ravindradevops72/ravi-image:v1 .

    - name: Docker Login  
      run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

    - name: Push Docker Image
      run: docker push ravindradevops72/ravi-image:v1

    - name: Create Container from Docker Image
      run: docker run -itd --name ravi-cont1 ravindradevops72/ravi-image:v1

    - name: Store Container logs into file
      run: docker logs ravi-cont1>/home/ubnutu/container_logs.txt



      